apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: zuzu-com-tw-tls
spec:
  secretName: zuzu-com-tw
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: zuzu.com.tw
  dnsNames:
  - k8s.zuzu.com.tw
  - zuzu.com.tw
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - k8s.zuzu.com.tw